### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by Schniz**
* Added env var for `spec` database
* Added a docker-based testing in `.travis.yml`
* Added badge to README

After merging:
* Register this repo to Travis CI
* Make it build weekly/daily, so we can enjoy the benefits of `couchdb:latest` and `crystal:nightly` images

### CODE REVIEW

**Comment by Schniz** [comment]
Seems like Travis works suuuuuper slow with Docker.
I think about using static binaries from releases 🤷‍♂️

**Comment by TechMagister** [comment]
Yes, we can try this, it'll be safer

**Comment by Schniz** [comment]
Can you please try to rebuild the master branch?

**Comment by Schniz** [comment]
I'll try to use CircleCI. I remember it to be faster. Also, @vladfaust recommended it as well!

**Pull request merged**
